[application]
name = "porto-app"
default_platform = "web"

[web.app]
title = "Daffa Karyudi | AI Software Engineer"

[web.watcher]
watch_path = ["porto-app", "porto-shared", "content", "public"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
