[application]
name = "web-porto-app"
default_platform = "web"

[web.app]
title = "web-porto"

[web.watcher]
watch_path = ["crates", "content"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
