name: Build and Push to Cachix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: porto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build .#default --accept-flake-config

      - name: Check
        run: |
          nix develop --accept-flake-config --command cargo fmt --all -- --check
          nix develop --accept-flake-config --command \
            cargo clippy --workspace --target wasm32-unknown-unknown --all-targets -- -D warnings
